- name: Install Httpd on RHEL
  hosts: all
  become: True
  become_method: sudo
  become_user: root
  gather_facts: no

  tasks:
    - name: Ensure httpd package installed
      yum:
        name: '{{ packages }}'
        state: present
        update_cache: false
      vars:
        packages:
          - httpd
    - name: Ensure Httpd service is enabled and started
      service:
        name: httpd
        state: started
    - command: systemctl status httpd
      register: httpd_status
    - debug:
        msg: "Service httpd status: '{{ httpd_status.stdout }}'"