- name: Install JDK on RHEL
  hosts: rhel
  become: True
  become_method: sudo
  become_user: root
  gather_facts: no

  tasks:
    - name: Ensure jdk package installed
      yum:
        name: '{{ packages }}'
        state: present
        update_cache: true
      vars:
        packages:
          - java-1.8.0-openjdk